name: Deploy A Preview Version Worker
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      deployment-url: ${{ steps.upload.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Build & Upload a Worker Version
        id: upload
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '4.18.0'
          command: versions upload
      - name: print deployment-url
        run: echo ${{ steps.upload.outputs.deployment-url }}
